[package]
name = "img-cmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
img_hash = "3.2.0"
sha-1 = "0.10.0"
