[package]
name = "img-cmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
image_hasher = "1.0.0"
sha-1 = "0.10.0"
serde = "1.0.133"
serde_json = "1.0.74"
colored = "2.0.0"
